<?php

return [
    [
        'bank_name' => '9  PAYMENT SOLUTIONS BANK',
        'bank_code' => '120001',
        'bank_type' => 'Merchant',
        'ussd_code' => null,
        'ussd_transfer_code' => null,
        'bank_logo' => 'https://api.live.redbiller.com/logos/bank/9psb.png',
        'country_code' => 'NG',
        'currency_code' => 'NGN',
    ],
    [
        'bank_name' => 'ABBEY MORTGAGE BANK',
        'bank_code' => '070010',
        'bank_type' => 'Mortgage',
        'ussd_code' => null,
        'ussd_transfer_code' => null,
        'bank_logo' => 'https://api.live.redbiller.com/logos/bank/default.png',
        'country_code' => 'NG',
        'currency_code' => 'NGN',
    ],
    [
        'bank_name' => 'ACCESS BANK',
        'bank_code' => '000014',
        'bank_type' => 'Commercial',
        'ussd_code' => '*901#',
        'ussd_transfer_code' => '*901*amount*account_no#',
        'bank_logo' => 'https://api.live.redbiller.com/logos/bank/access.png',
        'country_code' => 'NG',
        'currency_code' => 'NGN',
    ],
    [
        'bank_name' => 'ACCESSMOBILE',
        'bank_code' => '100013',
        'bank_type' => 'Merchant',
        'ussd_code' => null,
        'ussd_transfer_code' => null,
        'bank_logo' => 'https://api.live.redbiller.com/logos/bank/default.png',
        'country_code' => 'NG',
        'currency_code' => 'NGN',
    ],
    [
        'bank_name' => 'ACCION MICROFINANCE BANK',
        'bank_code' => '090134',
        'bank_type' => 'Microfinance',
        'ussd_code' => null,
        'ussd_transfer_code' => null,
        'bank_logo' => 'https://api.live.redbiller.com/logos/bank/accion.png',
        'country_code' => 'NG',
        'currency_code' => 'NGN',
    ],
    [
        'bank_name' => 'ADDOSSER MICROFINANCE BANK',
        'bank_code' => '090160',
        'bank_type' => 'Microfinance',
        'ussd_code' => null,
        'ussd_transfer_code' => null,
        'bank_logo' => 'https://api.live.redbiller.com/logos/bank/default.png',
        'country_code' => 'NG',
        'currency_code' => 'NGN',
    ],
    [
        'bank_name' => 'AG MORTGAGE BANK PLC',
        'bank_code' => '100028',
        'bank_type' => 'Mortgage',
        'ussd_code' => null,
        'ussd_transfer_code' => null,
        'bank_logo' => 'https://api.live.redbiller.com/logos/bank/default.png',
        'country_code' => 'NG',
        'currency_code' => 'NGN',
    ],
    [
        'bank_name' => 'AL-BARKAH MICROFINANCE BANK',
        'bank_code' => '090133',
        'bank_type' => 'Microfinance',
        'ussd_code' => null,
        'ussd_transfer_code' => null,
        'bank_logo' => 'https://api.live.redbiller.com/logos/bank/default.png',
        'country_code' => 'NG',
        'currency_code' => 'NGN',
    ],
    [
        'bank_name' => 'ALLWORKERS MICROFINANCE BANK',
        'bank_code' => '090131',
        'bank_type' => 'Microfinance',
        'ussd_code' => null,
        'ussd_transfer_code' => null,
        'bank_logo' => 'https://api.live.redbiller.com/logos/bank/default.png',
        'country_code' => 'NG',
        'currency_code' => 'NGN',
    ],
    [
        'bank_name' => 'ALPHA KAPITAL MICROFINANCE BANK',
        'bank_code' => '090169',
        'bank_type' => 'Microfinance',
        'ussd_code' => null,
        'ussd_transfer_code' => null,
        'bank_logo' => 'https://api.live.redbiller.com/logos/bank/default.png',
        'country_code' => 'NG',
        'currency_code' => 'NGN',
    ],
    [
        'bank_name' => 'AMJU MICROFINANCE BANK',
        'bank_code' => '090180',
        'bank_type' => 'Microfinance',
        'ussd_code' => null,
        'ussd_transfer_code' => null,
        'bank_logo' => 'https://api.live.redbiller.com/logos/bank/default.png',
        'country_code' => 'NG',
        'currency_code' => 'NGN',
    ],
    [
        'bank_name' => 'AMML MICROFINANCE BANK',
        'bank_code' => '090116',
        'bank_type' => 'Microfinance',
        'ussd_code' => null,
        'ussd_transfer_code' => null,
        'bank_logo' => 'https://api.live.redbiller.com/logos/bank/default.png',
        'country_code' => 'NG',
        'currency_code' => 'NGN',
    ],
    [
        'bank_name' => 'APEKS MICROFINANCE BANK',
        'bank_code' => '090143',
        'bank_type' => 'Microfinance',
        'ussd_code' => null,
        'ussd_transfer_code' => null,
        'bank_logo' => 'https://api.live.redbiller.com/logos/bank/default.png',
        'country_code' => 'NG',
        'currency_code' => 'NGN',
    ],
    [
        'bank_name' => 'ASOSAVINGS BANK',
        'bank_code' => '090001',
        'bank_type' => 'Mortgage',
        'ussd_code' => null,
        'ussd_transfer_code' => null,
        'bank_logo' => 'https://api.live.redbiller.com/logos/bank/aso.png',
        'country_code' => 'NG',
        'currency_code' => 'NGN',
    ],
    [
        'bank_name' => 'ASTRAPOLIS MICROFINANCE BANK',
        'bank_code' => '090172',
        'bank_type' => 'Microfinance',
        'ussd_code' => null,
        'ussd_transfer_code' => null,
        'bank_logo' => 'https://api.live.redbiller.com/logos/bank/default.png',
        'country_code' => 'NG',
        'currency_code' => 'NGN',
    ],
    [
        'bank_name' => 'BC KASH MICROFINANCE BANK',
        'bank_code' => '090127',
        'bank_type' => 'Microfinance',
        'ussd_code' => null,
        'ussd_transfer_code' => null,
        'bank_logo' => 'https://api.live.redbiller.com/logos/bank/default.png',
        'country_code' => 'NG',
        'currency_code' => 'NGN',
    ],
    [
        'bank_name' => 'BOCTRUST MICROFINANCE BANK',
        'bank_code' => '090117',
        'bank_type' => 'Microfinance',
        'ussd_code' => null,
        'ussd_transfer_code' => null,
        'bank_logo' => 'https://api.live.redbiller.com/logos/bank/default.png',
        'country_code' => 'NG',
        'currency_code' => 'NGN',
    ],
    [
        'bank_name' => 'BOSAK MICROFINANCE BANK',
        'bank_code' => '090176',
        'bank_type' => 'Microfinance',
        'ussd_code' => null,
        'ussd_transfer_code' => null,
        'bank_logo' => 'https://api.live.redbiller.com/logos/bank/default.png',
        'country_code' => 'NG',
        'currency_code' => 'NGN',
    ],
    [
        'bank_name' => 'BOWEN MICROFINANCE BANK',
        'bank_code' => '090148',
        'bank_type' => 'Microfinance',
        'ussd_code' => null,
        'ussd_transfer_code' => null,
        'bank_logo' => 'https://api.live.redbiller.com/logos/bank/default.png',
        'country_code' => 'NG',
        'currency_code' => 'NGN',
    ],
    [
        'bank_name' => 'BRENT GENERATION MORTGAGE BANK',
        'bank_code' => '070015',
        'bank_type' => 'Mortgage',
        'ussd_code' => null,
        'ussd_transfer_code' => null,
        'bank_logo' => 'https://api.live.redbiller.com/logos/bank/default.png',
        'country_code' => 'NG',
        'currency_code' => 'NGN',
    ],
    [
        'bank_name' => 'CARBON MICROFINANCE BANK (ONE FINANCE)',
        'bank_code' => '100026',
        'bank_type' => 'Microfinance',
        'ussd_code' => null,
        'ussd_transfer_code' => null,
        'bank_logo' => 'https://api.live.redbiller.com/logos/bank/default.png',
        'country_code' => 'NG',
        'currency_code' => 'NGN',
    ],
    [
        'bank_name' => 'CELLULANT',
        'bank_code' => '100005',
        'bank_type' => 'Merchant',
        'ussd_code' => null,
        'ussd_transfer_code' => null,
        'bank_logo' => 'https://api.live.redbiller.com/logos/bank/default.png',
        'country_code' => 'NG',
        'currency_code' => 'NGN',
    ],
    [
        'bank_name' => 'CEMCS MICROFINANCE BANK',
        'bank_code' => '090154',
        'bank_type' => 'Microfinance',
        'ussd_code' => null,
        'ussd_transfer_code' => null,
        'bank_logo' => 'https://api.live.redbiller.com/logos/bank/default.png',
        'country_code' => 'NG',
        'currency_code' => 'NGN',
    ],
    [
        'bank_name' => 'CHIKUM MICROFINANCE BANK',
        'bank_code' => '090141',
        'bank_type' => 'Microfinance',
        'ussd_code' => null,
        'ussd_transfer_code' => null,
        'bank_logo' => 'https://api.live.redbiller.com/logos/bank/default.png',
        'country_code' => 'NG',
        'currency_code' => 'NGN',
    ],
    [
        'bank_name' => 'CIT MICROFINANCE BANK',
        'bank_code' => '090144',
        'bank_type' => 'Microfinance',
        'ussd_code' => null,
        'ussd_transfer_code' => null,
        'bank_logo' => 'https://api.live.redbiller.com/logos/bank/default.png',
        'country_code' => 'NG',
        'currency_code' => 'NGN',
    ],
    [
        'bank_name' => 'CITIBANK NIGERIA',
        'bank_code' => '000009',
        'bank_type' => 'Commercial',
        'ussd_code' => null,
        'ussd_transfer_code' => null,
        'bank_logo' => 'https://api.live.redbiller.com/logos/bank/default.png',
        'country_code' => 'NG',
        'currency_code' => 'NGN',
    ],
    [
        'bank_name' => 'CONSUMER MICROFINANCE BANK',
        'bank_code' => '090130',
        'bank_type' => 'Microfinance',
        'ussd_code' => null,
        'ussd_transfer_code' => null,
        'bank_logo' => 'https://api.live.redbiller.com/logos/bank/default.png',
        'country_code' => 'NG',
        'currency_code' => 'NGN',
    ],
    [
        'bank_name' => 'CONTEC GLOBAL',
        'bank_code' => '100032',
        'bank_type' => 'Merchant',
        'ussd_code' => null,
        'ussd_transfer_code' => null,
        'bank_logo' => 'https://api.live.redbiller.com/logos/bank/nownow.png',
        'country_code' => 'NG',
        'currency_code' => 'NGN',
    ],
    [
        'bank_name' => 'CONVENANT MICROFINANCE BANK',
        'bank_code' => '070006',
        'bank_type' => 'Microfinance',
        'ussd_code' => null,
        'ussd_transfer_code' => null,
        'bank_logo' => 'https://api.live.redbiller.com/logos/bank/default.png',
        'country_code' => 'NG',
        'currency_code' => 'NGN',
    ],
    [
        'bank_name' => 'CORONATION BANK',
        'bank_code' => '060001',
        'bank_type' => 'Merchant',
        'ussd_code' => null,
        'ussd_transfer_code' => null,
        'bank_logo' => 'https://api.live.redbiller.com/logos/bank/default.png',
        'country_code' => 'NG',
        'currency_code' => 'NGN',
    ],
    [
        'bank_name' => 'CREDIT AFRIQUE MICROFINANCE BANK',
        'bank_code' => '090159',
        'bank_type' => 'Microfinance',
        'ussd_code' => null,
        'ussd_transfer_code' => null,
        'bank_logo' => 'https://api.live.redbiller.com/logos/bank/default.png',
        'country_code' => 'NG',
        'currency_code' => 'NGN',
    ],
    [
        'bank_name' => 'DAYLIGHT MICROFINANCE BANK',
        'bank_code' => '090167',
        'bank_type' => 'Microfinance',
        'ussd_code' => null,
        'ussd_transfer_code' => null,
        'bank_logo' => 'https://api.live.redbiller.com/logos/bank/default.png',
        'country_code' => 'NG',
        'currency_code' => 'NGN',
    ],
    [
        'bank_name' => 'E-BARCS MICROFINANCE BANK',
        'bank_code' => '090156',
        'bank_type' => 'Microfinance',
        'ussd_code' => null,
        'ussd_transfer_code' => null,
        'bank_logo' => 'https://api.live.redbiller.com/logos/bank/default.png',
        'country_code' => 'NG',
        'currency_code' => 'NGN',
    ],
    [
        'bank_name' => 'EARTHOLEUM',
        'bank_code' => '100021',
        'bank_type' => 'Merchant',
        'ussd_code' => null,
        'ussd_transfer_code' => null,
        'bank_logo' => 'https://api.live.redbiller.com/logos/bank/default.png',
        'country_code' => 'NG',
        'currency_code' => 'NGN',
    ],
    [
        'bank_name' => 'ECOBANK NIGERIA',
        'bank_code' => '000010',
        'bank_type' => 'Commercial',
        'ussd_code' => '*326#',
        'ussd_transfer_code' => null,
        'bank_logo' => 'https://api.live.redbiller.com/logos/bank/ecobank.png',
        'country_code' => 'NG',
        'currency_code' => 'NGN',
    ],
    [
        'bank_name' => 'ECOBANK XPRESS ACCOUNT',
        'bank_code' => '100008',
        'bank_type' => 'Merchant',
        'ussd_code' => null,
        'ussd_transfer_code' => null,
        'bank_logo' => 'https://api.live.redbiller.com/logos/bank/default.png',
        'country_code' => 'NG',
        'currency_code' => 'NGN',
    ],
    [
        'bank_name' => 'EKONDO MICROFINANCE BANK',
        'bank_code' => '090097',
        'bank_type' => 'Microfinance',
        'ussd_code' => null,
        'ussd_transfer_code' => null,
        'bank_logo' => 'https://api.live.redbiller.com/logos/bank/ekondo.png',
        'country_code' => 'NG',
        'currency_code' => 'NGN',
    ],
    [
        'bank_name' => 'EMPIRE MICROFINANCE BANK',
        'bank_code' => '090114',
        'bank_type' => 'Microfinance',
        'ussd_code' => null,
        'ussd_transfer_code' => null,
        'bank_logo' => 'https://api.live.redbiller.com/logos/bank/default.png',
        'country_code' => 'NG',
        'currency_code' => 'NGN',
    ],
    [
        'bank_name' => 'ESO-E MICROFINANCE BANK',
        'bank_code' => '090166',
        'bank_type' => 'Microfinance',
        'ussd_code' => null,
        'ussd_transfer_code' => null,
        'bank_logo' => 'https://api.live.redbiller.com/logos/bank/default.png',
        'country_code' => 'NG',
        'currency_code' => 'NGN',
    ],
    [
        'bank_name' => 'ETRANZACT',
        'bank_code' => '100006',
        'bank_type' => 'Merchant',
        'ussd_code' => null,
        'ussd_transfer_code' => null,
        'bank_logo' => 'https://api.live.redbiller.com/logos/bank/default.png',
        'country_code' => 'NG',
        'currency_code' => 'NGN',
    ],
    [
        'bank_name' => 'EYOWO MICROFINANCE BANK',
        'bank_code' => '090328',
        'bank_type' => 'Microfinance',
        'ussd_code' => null,
        'ussd_transfer_code' => null,
        'bank_logo' => 'https://api.live.redbiller.com/logos/bank/eyowo.png',
        'country_code' => 'NG',
        'currency_code' => 'NGN',
    ],
    [
        'bank_name' => 'FAIRMONEY MFB',
        'bank_code' => '090551',
        'bank_type' => 'Microfinance',
        'ussd_code' => null,
        'ussd_transfer_code' => null,
        'bank_logo' => 'https://api.live.redbiller.com/logos/bank/default.png',
        'country_code' => 'NG',
        'currency_code' => 'NGN',
    ],
    [
        'bank_name' => 'FAST MICROFINANCE BANK',
        'bank_code' => '090179',
        'bank_type' => 'Microfinance',
        'ussd_code' => null,
        'ussd_transfer_code' => null,
        'bank_logo' => 'https://api.live.redbiller.com/logos/bank/default.png',
        'country_code' => 'NG',
        'currency_code' => 'NGN',
    ],
    [
        'bank_name' => 'FBNMOBILE',
        'bank_code' => '100014',
        'bank_type' => 'Merchant',
        'ussd_code' => null,
        'ussd_transfer_code' => null,
        'bank_logo' => 'https://api.live.redbiller.com/logos/bank/default.png',
        'country_code' => 'NG',
        'currency_code' => 'NGN',
    ],
    [
        'bank_name' => 'FBNQUEST BANK',
        'bank_code' => '060002',
        'bank_type' => 'Merchant',
        'ussd_code' => null,
        'ussd_transfer_code' => null,
        'bank_logo' => 'https://api.live.redbiller.com/logos/bank/default.png',
        'country_code' => 'NG',
        'currency_code' => 'NGN',
    ],
    [
        'bank_name' => 'FCMB MOBILE',
        'bank_code' => '100031',
        'bank_type' => 'Merchant',
        'ussd_code' => null,
        'ussd_transfer_code' => null,
        'bank_logo' => 'https://api.live.redbiller.com/logos/bank/default.png',
        'country_code' => 'NG',
        'currency_code' => 'NGN',
    ],
    [
        'bank_name' => 'FETS MICROFINANCE BANK',
        'bank_code' => '100001',
        'bank_type' => 'Microfinance',
        'ussd_code' => null,
        'ussd_transfer_code' => null,
        'bank_logo' => 'https://api.live.redbiller.com/logos/bank/default.png',
        'country_code' => 'NG',
        'currency_code' => 'NGN',
    ],
    [
        'bank_name' => 'FFS MICROFINANCE BANK',
        'bank_code' => '090153',
        'bank_type' => 'Microfinance',
        'ussd_code' => null,
        'ussd_transfer_code' => null,
        'bank_logo' => 'https://api.live.redbiller.com/logos/bank/default.png',
        'country_code' => 'NG',
        'currency_code' => 'NGN',
    ],
    [
        'bank_name' => 'FIDELITY BANK',
        'bank_code' => '000007',
        'bank_type' => 'Commercial',
        'ussd_code' => '*770#',
        'ussd_transfer_code' => '*770*account_no*amount#',
        'bank_logo' => 'https://api.live.redbiller.com/logos/bank/fidelity.png',
        'country_code' => 'NG',
        'currency_code' => 'NGN',
    ],
    [
        'bank_name' => 'FIDELITY MOBILE',
        'bank_code' => '100019',
        'bank_type' => 'Merchant',
        'ussd_code' => null,
        'ussd_transfer_code' => null,
        'bank_logo' => 'https://api.live.redbiller.com/logos/bank/default.png',
        'country_code' => 'NG',
        'currency_code' => 'NGN',
    ],
    [
        'bank_name' => 'FIDFUND MICROFINANCE BANK',
        'bank_code' => '090126',
        'bank_type' => 'Microfinance',
        'ussd_code' => null,
        'ussd_transfer_code' => null,
        'bank_logo' => 'https://api.live.redbiller.com/logos/bank/default.png',
        'country_code' => 'NG',
        'currency_code' => 'NGN',
    ],
    [
        'bank_name' => 'FINATRUST MICROFINANCE BANK',
        'bank_code' => '090111',
        'bank_type' => 'Microfinance',
        'ussd_code' => null,
        'ussd_transfer_code' => null,
        'bank_logo' => 'https://api.live.redbiller.com/logos/bank/default.png',
        'country_code' => 'NG',
        'currency_code' => 'NGN',
    ],
    [
        'bank_name' => 'FIRST CITY MONUMENT BANK',
        'bank_code' => '000003',
        'bank_type' => 'Commercial',
        'ussd_code' => '*329#',
        'ussd_transfer_code' => '*329*amount*account_no#',
        'bank_logo' => 'https://api.live.redbiller.com/logos/bank/fcmb.png',
        'country_code' => 'NG',
        'currency_code' => 'NGN',
    ],
    [
        'bank_name' => 'FIRST GENERATION MORTGAGE BANK',
        'bank_code' => '070014',
        'bank_type' => 'Mortgage',
        'ussd_code' => null,
        'ussd_transfer_code' => null,
        'bank_logo' => 'https://api.live.redbiller.com/logos/bank/default.png',
        'country_code' => 'NG',
        'currency_code' => 'NGN',
    ],
    [
        'bank_name' => 'FIRST MULTIPLE MICROFINANCE BANK',
        'bank_code' => '090163',
        'bank_type' => 'Microfinance',
        'ussd_code' => null,
        'ussd_transfer_code' => null,
        'bank_logo' => 'https://api.live.redbiller.com/logos/bank/default.png',
        'country_code' => 'NG',
        'currency_code' => 'NGN',
    ],
    [
        'bank_name' => 'FIRST ROYAL MICROFINANCE BANK',
        'bank_code' => '090164',
        'bank_type' => 'Microfinance',
        'ussd_code' => null,
        'ussd_transfer_code' => null,
        'bank_logo' => 'https://api.live.redbiller.com/logos/bank/default.png',
        'country_code' => 'NG',
        'currency_code' => 'NGN',
    ],
    [
        'bank_name' => 'FIRSTBANK OF NIGERIA',
        'bank_code' => '000016',
        'bank_type' => 'Commercial',
        'ussd_code' => '*894#',
        'ussd_transfer_code' => '*894*amount*account_no#',
        'bank_logo' => 'https://api.live.redbiller.com/logos/bank/firstbank.png',
        'country_code' => 'NG',
        'currency_code' => 'NGN',
    ],
    [
        'bank_name' => 'FLUTTERWAVE TECHNOLOGY SOLUTIONS LIMITED',
        'bank_code' => '110002',
        'bank_type' => 'Merchant',
        'ussd_code' => null,
        'ussd_transfer_code' => null,
        'bank_logo' => 'https://api.live.redbiller.com/logos/bank/flutterwave.png',
        'country_code' => 'NG',
        'currency_code' => 'NGN',
    ],
    [
        'bank_name' => 'FNB MORTGAGES BANK',
        'bank_code' => '090107',
        'bank_type' => 'Mortgage',
        'ussd_code' => null,
        'ussd_transfer_code' => null,
        'bank_logo' => 'https://api.live.redbiller.com/logos/bank/default.png',
        'country_code' => 'NG',
        'currency_code' => 'NGN',
    ],
    [
        'bank_name' => 'FORTIS MICROFINANCE BANK',
        'bank_code' => '070002',
        'bank_type' => 'Microfinance',
        'ussd_code' => null,
        'ussd_transfer_code' => null,
        'bank_logo' => 'https://api.live.redbiller.com/logos/bank/default.png',
        'country_code' => 'NG',
        'currency_code' => 'NGN',
    ],
    [
        'bank_name' => 'FORTISMOBILE',
        'bank_code' => '100016',
        'bank_type' => 'Merchant',
        'ussd_code' => null,
        'ussd_transfer_code' => null,
        'bank_logo' => 'https://api.live.redbiller.com/logos/bank/default.png',
        'country_code' => 'NG',
        'currency_code' => 'NGN',
    ],
    [
        'bank_name' => 'FSDH',
        'bank_code' => '400001',
        'bank_type' => 'Merchant',
        'ussd_code' => null,
        'ussd_transfer_code' => null,
        'bank_logo' => 'https://api.live.redbiller.com/logos/bank/default.png',
        'country_code' => 'NG',
        'currency_code' => 'NGN',
    ],
    [
        'bank_name' => 'FULLRANGE MICROFINANCE BANK',
        'bank_code' => '090145',
        'bank_type' => 'Microfinance',
        'ussd_code' => null,
        'ussd_transfer_code' => null,
        'bank_logo' => 'https://api.live.redbiller.com/logos/bank/default.png',
        'country_code' => 'NG',
        'currency_code' => 'NGN',
    ],
    [
        'bank_name' => 'FUTO MICROFINANCE BANK',
        'bank_code' => '090158',
        'bank_type' => 'Microfinance',
        'ussd_code' => null,
        'ussd_transfer_code' => null,
        'bank_logo' => 'https://api.live.redbiller.com/logos/bank/default.png',
        'country_code' => 'NG',
        'currency_code' => 'NGN',
    ],
    [
        'bank_name' => 'GASHUA MICROFINANCE BANK',
        'bank_code' => '090168',
        'bank_type' => 'Microfinance',
        'ussd_code' => null,
        'ussd_transfer_code' => null,
        'bank_logo' => 'https://api.live.redbiller.com/logos/bank/default.png',
        'country_code' => 'NG',
        'currency_code' => 'NGN',
    ],
    [
        'bank_name' => 'GATEWAY MORTGAGE BANK',
        'bank_code' => '070009',
        'bank_type' => 'Mortgage',
        'ussd_code' => null,
        'ussd_transfer_code' => null,
        'bank_logo' => 'https://api.live.redbiller.com/logos/bank/default.png',
        'country_code' => 'NG',
        'currency_code' => 'NGN',
    ],
    [
        'bank_name' => 'GLOBUS BANK',
        'bank_code' => '000027',
        'bank_type' => 'Commercial',
        'ussd_code' => null,
        'ussd_transfer_code' => null,
        'bank_logo' => 'https://api.live.redbiller.com/logos/bank/default.png',
        'country_code' => 'NG',
        'currency_code' => 'NGN',
    ],
    [
        'bank_name' => 'GOWANS MICROFINANCE BANK',
        'bank_code' => '090122',
        'bank_type' => 'Microfinance',
        'ussd_code' => null,
        'ussd_transfer_code' => null,
        'bank_logo' => 'https://api.live.redbiller.com/logos/bank/default.png',
        'country_code' => 'NG',
        'currency_code' => 'NGN',
    ],
    [
        'bank_name' => 'GREENBANK MICROFINANCE BANK',
        'bank_code' => '090178',
        'bank_type' => 'Microfinance',
        'ussd_code' => null,
        'ussd_transfer_code' => null,
        'bank_logo' => 'https://api.live.redbiller.com/logos/bank/default.png',
        'country_code' => 'NG',
        'currency_code' => 'NGN',
    ],
    [
        'bank_name' => 'GTMOBILE',
        'bank_code' => '100009',
        'bank_type' => 'Merchant',
        'ussd_code' => null,
        'ussd_transfer_code' => null,
        'bank_logo' => 'https://api.live.redbiller.com/logos/bank/default.png',
        'country_code' => 'NG',
        'currency_code' => 'NGN',
    ],
    [
        'bank_name' => 'GUARANTY TRUST BANK',
        'bank_code' => '000013',
        'bank_type' => 'Commercial',
        'ussd_code' => '*737#',
        'ussd_transfer_code' => '*737*2*amount*account_no#',
        'bank_logo' => 'https://api.live.redbiller.com/logos/bank/gtb.png',
        'country_code' => 'NG',
        'currency_code' => 'NGN',
    ],
    [
        'bank_name' => 'HACKMAN MICROFINANCE BANK',
        'bank_code' => '090147',
        'bank_type' => 'Microfinance',
        'ussd_code' => null,
        'ussd_transfer_code' => null,
        'bank_logo' => 'https://api.live.redbiller.com/logos/bank/default.png',
        'country_code' => 'NG',
        'currency_code' => 'NGN',
    ],
    [
        'bank_name' => 'HAGGAI MORTGAGE BANK',
        'bank_code' => '070017',
        'bank_type' => 'Mortgage',
        'ussd_code' => null,
        'ussd_transfer_code' => null,
        'bank_logo' => 'https://api.live.redbiller.com/logos/bank/default.png',
        'country_code' => 'NG',
        'currency_code' => 'NGN',
    ],
    [
        'bank_name' => 'HASAL MICROFINANCE BANK',
        'bank_code' => '090121',
        'bank_type' => 'Microfinance',
        'ussd_code' => null,
        'ussd_transfer_code' => null,
        'bank_logo' => 'https://api.live.redbiller.com/logos/bank/default.png',
        'country_code' => 'NG',
        'currency_code' => 'NGN',
    ],
    [
        'bank_name' => 'HEDONMARK',
        'bank_code' => '100017',
        'bank_type' => 'Merchant',
        'ussd_code' => null,
        'ussd_transfer_code' => null,
        'bank_logo' => 'https://api.live.redbiller.com/logos/bank/default.png',
        'country_code' => 'NG',
        'currency_code' => 'NGN',
    ],
    [
        'bank_name' => 'HERITAGE BANK',
        'bank_code' => '000020',
        'bank_type' => 'Commercial',
        'ussd_code' => '*322#',
        'ussd_transfer_code' => '*322*030*account_no*amount#',
        'bank_logo' => 'https://api.live.redbiller.com/logos/bank/heritage.png',
        'country_code' => 'NG',
        'currency_code' => 'NGN',
    ],
    [
        'bank_name' => 'IBILE MICROFINANCE BANK',
        'bank_code' => '090118',
        'bank_type' => 'Microfinance',
        'ussd_code' => null,
        'ussd_transfer_code' => null,
        'bank_logo' => 'https://api.live.redbiller.com/logos/bank/default.png',
        'country_code' => 'NG',
        'currency_code' => 'NGN',
    ],
    [
        'bank_name' => 'IMPERIAL HOMES MORTGAGE BANK',
        'bank_code' => '100024',
        'bank_type' => 'Mortgage',
        'ussd_code' => null,
        'ussd_transfer_code' => null,
        'bank_logo' => 'https://api.live.redbiller.com/logos/bank/default.png',
        'country_code' => 'NG',
        'currency_code' => 'NGN',
    ],
    [
        'bank_name' => 'INFINITY MICROFINANCE BANK',
        'bank_code' => '090157',
        'bank_type' => 'Microfinance',
        'ussd_code' => null,
        'ussd_transfer_code' => null,
        'bank_logo' => 'https://api.live.redbiller.com/logos/bank/default.png',
        'country_code' => 'NG',
        'currency_code' => 'NGN',
    ],
    [
        'bank_name' => 'INFINITY TRUST GENERATION MORTGAGE BANK',
        'bank_code' => '070016',
        'bank_type' => 'Mortgage',
        'ussd_code' => null,
        'ussd_transfer_code' => null,
        'bank_logo' => 'https://api.live.redbiller.com/logos/bank/default.png',
        'country_code' => 'NG',
        'currency_code' => 'NGN',
    ],
    [
        'bank_name' => 'INNOVECTIVES KESH',
        'bank_code' => '100029',
        'bank_type' => 'Merchant',
        'ussd_code' => null,
        'ussd_transfer_code' => null,
        'bank_logo' => 'https://api.live.redbiller.com/logos/bank/default.png',
        'country_code' => 'NG',
        'currency_code' => 'NGN',
    ],
    [
        'bank_name' => 'INTELLIFIN',
        'bank_code' => '100027',
        'bank_type' => 'Merchant',
        'ussd_code' => null,
        'ussd_transfer_code' => null,
        'bank_logo' => 'https://api.live.redbiller.com/logos/bank/default.png',
        'country_code' => 'NG',
        'currency_code' => 'NGN',
    ],
    [
        'bank_name' => 'IRL MICROFINANCE BANK',
        'bank_code' => '090149',
        'bank_type' => 'Microfinance',
        'ussd_code' => null,
        'ussd_transfer_code' => null,
        'bank_logo' => 'https://api.live.redbiller.com/logos/bank/default.png',
        'country_code' => 'NG',
        'currency_code' => 'NGN',
    ],
    [
        'bank_name' => 'JAIZ BANK',
        'bank_code' => '000006',
        'bank_type' => 'Commercial',
        'ussd_code' => '*389#',
        'ussd_transfer_code' => '*389*301*account_no*amount#',
        'bank_logo' => 'https://api.live.redbiller.com/logos/bank/default.png',
        'country_code' => 'NG',
        'currency_code' => 'NGN',
    ],
    [
        'bank_name' => 'JUBILEELIFE BANK',
        'bank_code' => '090003',
        'bank_type' => 'Mortgage',
        'ussd_code' => null,
        'ussd_transfer_code' => null,
        'bank_logo' => 'https://api.live.redbiller.com/logos/bank/default.png',
        'country_code' => 'NG',
        'currency_code' => 'NGN',
    ],
    [
        'bank_name' => 'KEGOW',
        'bank_code' => '100015',
        'bank_type' => 'Merchant',
        'ussd_code' => null,
        'ussd_transfer_code' => null,
        'bank_logo' => 'https://api.live.redbiller.com/logos/bank/default.png',
        'country_code' => 'NG',
        'currency_code' => 'NGN',
    ],
    [
        'bank_name' => 'KEYSTONE BANK',
        'bank_code' => '000002',
        'bank_type' => 'Commercial',
        'ussd_code' => '*7111#',
        'ussd_transfer_code' => '*7111*amount*account_no#',
        'bank_logo' => 'https://api.live.redbiller.com/logos/bank/keystone.png',
        'country_code' => 'NG',
        'currency_code' => 'NGN',
    ],
    [
        'bank_name' => 'KUDA MICROFINANCE BANK',
        'bank_code' => '090267',
        'bank_type' => 'Microfinance',
        'ussd_code' => null,
        'ussd_transfer_code' => null,
        'bank_logo' => 'https://api.live.redbiller.com/logos/bank/kuda.png',
        'country_code' => 'NG',
        'currency_code' => 'NGN',
    ],
    [
        'bank_name' => 'LAFAYETTE MICROFINANCE BANK',
        'bank_code' => '090155',
        'bank_type' => 'Microfinance',
        'ussd_code' => null,
        'ussd_transfer_code' => null,
        'bank_logo' => 'https://api.live.redbiller.com/logos/bank/default.png',
        'country_code' => 'NG',
        'currency_code' => 'NGN',
    ],
    [
        'bank_name' => 'LAPO MICROFINANCE BANK',
        'bank_code' => '090177',
        'bank_type' => 'Microfinance',
        'ussd_code' => null,
        'ussd_transfer_code' => null,
        'bank_logo' => 'https://api.live.redbiller.com/logos/bank/default.png',
        'country_code' => 'NG',
        'currency_code' => 'NGN',
    ],
    [
        'bank_name' => 'LBIC MORTGAGE BANK',
        'bank_code' => '070012',
        'bank_type' => 'Mortgage',
        'ussd_code' => null,
        'ussd_transfer_code' => null,
        'bank_logo' => 'https://api.live.redbiller.com/logos/bank/default.png',
        'country_code' => 'NG',
        'currency_code' => 'NGN',
    ],
    [
        'bank_name' => 'MAINSTREET MICROFINANCE BANK',
        'bank_code' => '090171',
        'bank_type' => 'Microfinance',
        'ussd_code' => null,
        'ussd_transfer_code' => null,
        'bank_logo' => 'https://api.live.redbiller.com/logos/bank/mainstreet.png',
        'country_code' => 'NG',
        'currency_code' => 'NGN',
    ],
    [
        'bank_name' => 'MALACHY MICROFINANCE BANK',
        'bank_code' => '090174',
        'bank_type' => 'Microfinance',
        'ussd_code' => null,
        'ussd_transfer_code' => null,
        'bank_logo' => 'https://api.live.redbiller.com/logos/bank/default.png',
        'country_code' => 'NG',
        'currency_code' => 'NGN',
    ],
    [
        'bank_name' => 'MICROCRED MICROFINANCE BANK',
        'bank_code' => '090136',
        'bank_type' => 'Microfinance',
        'ussd_code' => null,
        'ussd_transfer_code' => null,
        'bank_logo' => 'https://api.live.redbiller.com/logos/bank/default.png',
        'country_code' => 'NG',
        'currency_code' => 'NGN',
    ],
    [
        'bank_name' => 'MKUDI',
        'bank_code' => '100011',
        'bank_type' => 'Merchant',
        'ussd_code' => null,
        'ussd_transfer_code' => null,
        'bank_logo' => 'https://api.live.redbiller.com/logos/bank/default.png',
        'country_code' => 'NG',
        'currency_code' => 'NGN',
    ],
    [
        'bank_name' => 'MONEYBOX',
        'bank_code' => '100020',
        'bank_type' => 'Merchant',
        'ussd_code' => null,
        'ussd_transfer_code' => null,
        'bank_logo' => 'https://api.live.redbiller.com/logos/bank/default.png',
        'country_code' => 'NG',
        'currency_code' => 'NGN',
    ],
    [
        'bank_name' => 'MONEYTRUST MICROFINANCE BANK',
        'bank_code' => '090129',
        'bank_type' => 'Microfinance',
        'ussd_code' => null,
        'ussd_transfer_code' => null,
        'bank_logo' => 'https://api.live.redbiller.com/logos/bank/default.png',
        'country_code' => 'NG',
        'currency_code' => 'NGN',
    ],
    [
        'bank_name' => 'MONIEPOINT MICROFINANCE BANK',
        'bank_code' => '090405',
        'bank_type' => 'Microfinance',
        'ussd_code' => null,
        'ussd_transfer_code' => null,
        'bank_logo' => 'https://api.live.redbiller.com/logos/bank/moniepoint.png',
        'country_code' => 'NG',
        'currency_code' => 'NGN',
    ],
    [
        'bank_name' => 'MUTUAL TRUST MICROFINANCE BANK',
        'bank_code' => '090151',
        'bank_type' => 'Microfinance',
        'ussd_code' => null,
        'ussd_transfer_code' => null,
        'bank_logo' => 'https://api.live.redbiller.com/logos/bank/default.png',
        'country_code' => 'NG',
        'currency_code' => 'NGN',
    ],
    [
        'bank_name' => 'NARGATA MICROFINANCE BANK',
        'bank_code' => '090152',
        'bank_type' => 'Microfinance',
        'ussd_code' => null,
        'ussd_transfer_code' => null,
        'bank_logo' => 'https://api.live.redbiller.com/logos/bank/default.png',
        'country_code' => 'NG',
        'currency_code' => 'NGN',
    ],
    [
        'bank_name' => 'NDIORAH MICROFINANCE BANK',
        'bank_code' => '090128',
        'bank_type' => 'Microfinance',
        'ussd_code' => null,
        'ussd_transfer_code' => null,
        'bank_logo' => 'https://api.live.redbiller.com/logos/bank/default.png',
        'country_code' => 'NG',
        'currency_code' => 'NGN',
    ],
    [
        'bank_name' => 'NEW PRUDENTIAL BANK',
        'bank_code' => '090108',
        'bank_type' => 'Commercial',
        'ussd_code' => null,
        'ussd_transfer_code' => null,
        'bank_logo' => 'https://api.live.redbiller.com/logos/bank/default.png',
        'country_code' => 'NG',
        'currency_code' => 'NGN',
    ],
    [
        'bank_name' => 'NIP VIRTUAL BANK',
        'bank_code' => '999999',
        'bank_type' => 'Merchant',
        'ussd_code' => null,
        'ussd_transfer_code' => null,
        'bank_logo' => 'https://api.live.redbiller.com/logos/bank/default.png',
        'country_code' => 'NG',
        'currency_code' => 'NGN',
    ],
    [
        'bank_name' => 'NOVA MERCHANT BANK',
        'bank_code' => '060003',
        'bank_type' => 'Merchant',
        'ussd_code' => null,
        'ussd_transfer_code' => null,
        'bank_logo' => 'https://api.live.redbiller.com/logos/bank/default.png',
        'country_code' => 'NG',
        'currency_code' => 'NGN',
    ],
    [
        'bank_name' => 'NPF MICROFINANCE BANK',
        'bank_code' => '070001',
        'bank_type' => 'Microfinance',
        'ussd_code' => null,
        'ussd_transfer_code' => null,
        'bank_logo' => 'https://api.live.redbiller.com/logos/bank/default.png',
        'country_code' => 'NG',
        'currency_code' => 'NGN',
    ],
    [
        'bank_name' => 'OHAFIA MICROFINANCE BANK',
        'bank_code' => '090119',
        'bank_type' => '',
        'ussd_code' => null,
        'ussd_transfer_code' => null,
        'bank_logo' => 'https://api.live.redbiller.com/logos/bank/default.png',
        'country_code' => 'NG',
        'currency_code' => 'NGN',
    ],
    [
        'bank_name' => 'OKPOGA MICROFINANCE BANK',
        'bank_code' => '090161',
        'bank_type' => 'Microfinance',
        'ussd_code' => null,
        'ussd_transfer_code' => null,
        'bank_logo' => 'https://api.live.redbiller.com/logos/bank/default.png',
        'country_code' => 'NG',
        'currency_code' => 'NGN',
    ],
    [
        'bank_name' => 'OMOLUABI MORTGAGE BANK',
        'bank_code' => '070007',
        'bank_type' => 'Mortgage',
        'ussd_code' => null,
        'ussd_transfer_code' => null,
        'bank_logo' => 'https://api.live.redbiller.com/logos/bank/default.png',
        'country_code' => 'NG',
        'currency_code' => 'NGN',
    ],
    [
        'bank_name' => 'OPAY',
        'bank_code' => '100004',
        'bank_type' => 'Merchant',
        'ussd_code' => null,
        'ussd_transfer_code' => null,
        'bank_logo' => 'https://api.live.redbiller.com/logos/bank/opay.png',
        'country_code' => 'NG',
        'currency_code' => 'NGN',
    ],
    [
        'bank_name' => 'PAGA',
        'bank_code' => '100002',
        'bank_type' => 'Microfinance',
        'ussd_code' => null,
        'ussd_transfer_code' => null,
        'bank_logo' => 'https://api.live.redbiller.com/logos/bank/paga.png',
        'country_code' => 'NG',
        'currency_code' => 'NGN',
    ],
    [
        'bank_name' => 'PAGE MICROFINANCE BANK',
        'bank_code' => '070008',
        'bank_type' => 'Microfinance',
        'ussd_code' => null,
        'ussd_transfer_code' => null,
        'bank_logo' => 'https://api.live.redbiller.com/logos/bank/default.png',
        'country_code' => 'NG',
        'currency_code' => 'NGN',
    ],
    [
        'bank_name' => 'PALMPAY',
        'bank_code' => '100033',
        'bank_type' => 'Microfinance',
        'ussd_code' => null,
        'ussd_transfer_code' => null,
        'bank_logo' => 'https://api.live.redbiller.com/logos/bank/default.png',
        'country_code' => 'NG',
        'currency_code' => 'NGN',
    ],
    [
        'bank_name' => 'PARKWAY-READYCASH MICROFINANCE BANK',
        'bank_code' => '100003',
        'bank_type' => 'Microfinance',
        'ussd_code' => null,
        'ussd_transfer_code' => null,
        'bank_logo' => 'https://api.live.redbiller.com/logos/bank/default.png',
        'country_code' => 'NG',
        'currency_code' => 'NGN',
    ],
    [
        'bank_name' => 'PAYATTITUDE ONLINE',
        'bank_code' => '110001',
        'bank_type' => 'Merchant',
        'ussd_code' => null,
        'ussd_transfer_code' => null,
        'bank_logo' => 'https://api.live.redbiller.com/logos/bank/default.png',
        'country_code' => 'NG',
        'currency_code' => 'NGN',
    ],
    [
        'bank_name' => 'PECAN TRUST MICROFINANCE BANK',
        'bank_code' => '090137',
        'bank_type' => 'Microfinance',
        'ussd_code' => null,
        'ussd_transfer_code' => null,
        'bank_logo' => 'https://api.live.redbiller.com/logos/bank/default.png',
        'country_code' => 'NG',
        'currency_code' => 'NGN',
    ],
    [
        'bank_name' => 'PERSONAL TRUST MICROFINANCE BANK',
        'bank_code' => '090135',
        'bank_type' => 'Microfinance',
        'ussd_code' => null,
        'ussd_transfer_code' => null,
        'bank_logo' => 'https://api.live.redbiller.com/logos/bank/default.png',
        'country_code' => 'NG',
        'currency_code' => 'NGN',
    ],
    [
        'bank_name' => 'PETRA MICROFINANCE BANK',
        'bank_code' => '090165',
        'bank_type' => 'Microfinance',
        'ussd_code' => null,
        'ussd_transfer_code' => null,
        'bank_logo' => 'https://api.live.redbiller.com/logos/bank/default.png',
        'country_code' => 'NG',
        'currency_code' => 'NGN',
    ],
    [
        'bank_name' => 'PLATINUM MORTGAGE BANK',
        'bank_code' => '070013',
        'bank_type' => 'Mortgage',
        'ussd_code' => null,
        'ussd_transfer_code' => null,
        'bank_logo' => 'https://api.live.redbiller.com/logos/bank/default.png',
        'country_code' => 'NG',
        'currency_code' => 'NGN',
    ],
    [
        'bank_name' => 'POLARIS BANK',
        'bank_code' => '000008',
        'bank_type' => 'Commercial',
        'ussd_code' => '*833#',
        'ussd_transfer_code' => '*833*amount*account_no#',
        'bank_logo' => 'https://api.live.redbiller.com/logos/bank/polaris.png',
        'country_code' => 'NG',
        'currency_code' => 'NGN',
    ],
    [
        'bank_name' => 'PRALLEX BANK',
        'bank_code' => '090004',
        'bank_type' => 'Microfinance',
        'ussd_code' => null,
        'ussd_transfer_code' => null,
        'bank_logo' => 'https://api.live.redbiller.com/logos/bank/default.png',
        'country_code' => 'NG',
        'currency_code' => 'NGN',
    ],
    [
        'bank_name' => 'PROVIDUS BANK',
        'bank_code' => '000023',
        'bank_type' => 'Commercial',
        'ussd_code' => null,
        'ussd_transfer_code' => null,
        'bank_logo' => 'https://api.live.redbiller.com/logos/bank/providus.png',
        'country_code' => 'NG',
        'currency_code' => 'NGN',
    ],
    [
        'bank_name' => 'RAHAMA MICROFINANCE BANK',
        'bank_code' => '090170',
        'bank_type' => 'Microfinance',
        'ussd_code' => null,
        'ussd_transfer_code' => null,
        'bank_logo' => 'https://api.live.redbiller.com/logos/bank/default.png',
        'country_code' => 'NG',
        'currency_code' => 'NGN',
    ],
    [
        'bank_name' => 'RAND MERCHANT BANK',
        'bank_code' => '000024',
        'bank_type' => 'Merchant',
        'ussd_code' => null,
        'ussd_transfer_code' => null,
        'bank_logo' => 'https://api.live.redbiller.com/logos/bank/default.png',
        'country_code' => 'NG',
        'currency_code' => 'NGN',
    ],
    [
        'bank_name' => 'REFUGE MORTGAGE BANK',
        'bank_code' => '070011',
        'bank_type' => 'Mortgage',
        'ussd_code' => null,
        'ussd_transfer_code' => null,
        'bank_logo' => 'https://api.live.redbiller.com/logos/bank/default.png',
        'country_code' => 'NG',
        'currency_code' => 'NGN',
    ],
    [
        'bank_name' => 'REGENT MICROFINANCE BANK',
        'bank_code' => '090125',
        'bank_type' => 'Microfinance',
        'ussd_code' => null,
        'ussd_transfer_code' => null,
        'bank_logo' => 'https://api.live.redbiller.com/logos/bank/default.png',
        'country_code' => 'NG',
        'currency_code' => 'NGN',
    ],
    [
        'bank_name' => 'RELIANCE MICROFINANCE BANK',
        'bank_code' => '090173',
        'bank_type' => 'Microfinance',
        'ussd_code' => null,
        'ussd_transfer_code' => null,
        'bank_logo' => 'https://api.live.redbiller.com/logos/bank/default.png',
        'country_code' => 'NG',
        'currency_code' => 'NGN',
    ],
    [
        'bank_name' => 'RICHWAY MICROFINANCE BANK',
        'bank_code' => '090132',
        'bank_type' => 'Microfinance',
        'ussd_code' => null,
        'ussd_transfer_code' => null,
        'bank_logo' => 'https://api.live.redbiller.com/logos/bank/default.png',
        'country_code' => 'NG',
        'currency_code' => 'NGN',
    ],
    [
        'bank_name' => 'ROLEZ MICROFINANCE BANK',
        'bank_code' => '50515',
        'bank_type' => 'Microfinance',
        'ussd_code' => null,
        'ussd_transfer_code' => null,
        'bank_logo' => 'https://api.live.redbiller.com/logos/bank/default.png',
        'country_code' => 'NG',
        'currency_code' => 'NGN',
    ],
    [
        'bank_name' => 'ROYAL EXCHANGE MICROFINANCE BANK',
        'bank_code' => '090138',
        'bank_type' => 'Microfinance',
        'ussd_code' => null,
        'ussd_transfer_code' => null,
        'bank_logo' => 'https://api.live.redbiller.com/logos/bank/default.png',
        'country_code' => 'NG',
        'currency_code' => 'NGN',
    ],
    [
        'bank_name' => 'RUBIES MICROFINANCE BANK',
        'bank_code' => '090175',
        'bank_type' => 'Microfinance',
        'ussd_code' => null,
        'ussd_transfer_code' => null,
        'bank_logo' => 'https://api.live.redbiller.com/logos/bank/default.png',
        'country_code' => 'NG',
        'currency_code' => 'NGN',
    ],
    [
        'bank_name' => 'SAGAMU MICROFINANCE BANK',
        'bank_code' => '090140',
        'bank_type' => 'Microfinance',
        'ussd_code' => null,
        'ussd_transfer_code' => null,
        'bank_logo' => 'https://api.live.redbiller.com/logos/bank/default.png',
        'country_code' => 'NG',
        'currency_code' => 'NGN',
    ],
    [
        'bank_name' => 'SAVETRUST BANK',
        'bank_code' => '090006',
        'bank_type' => 'Commercial',
        'ussd_code' => null,
        'ussd_transfer_code' => null,
        'bank_logo' => 'https://api.live.redbiller.com/logos/bank/default.png',
        'country_code' => 'NG',
        'currency_code' => 'NGN',
    ],
    [
        'bank_name' => 'SEED CAPITAL MICROFINANCE BANK',
        'bank_code' => '090112',
        'bank_type' => 'Microfinance',
        'ussd_code' => null,
        'ussd_transfer_code' => null,
        'bank_logo' => 'https://api.live.redbiller.com/logos/bank/default.png',
        'country_code' => 'NG',
        'currency_code' => 'NGN',
    ],
    [
        'bank_name' => 'SPARKLE MICROFINANCE BANK',
        'bank_code' => '090325',
        'bank_type' => 'Microfinance',
        'ussd_code' => null,
        'ussd_transfer_code' => null,
        'bank_logo' => 'https://api.live.redbiller.com/logos/bank/sparkle.png',
        'country_code' => 'NG',
        'currency_code' => 'NGN',
    ],
    [
        'bank_name' => 'STANBIC IBTC BANK',
        'bank_code' => '000012',
        'bank_type' => 'Commercial',
        'ussd_code' => '*909#',
        'ussd_transfer_code' => '*909*11*amount*account_no#',
        'bank_logo' => 'https://api.live.redbiller.com/logos/bank/stanbic.png',
        'country_code' => 'NG',
        'currency_code' => 'NGN',
    ],
    [
        'bank_name' => 'STANBICMOBILEMONEY',
        'bank_code' => '100007',
        'bank_type' => 'Merchant',
        'ussd_code' => null,
        'ussd_transfer_code' => null,
        'bank_logo' => 'https://api.live.redbiller.com/logos/bank/default.png',
        'country_code' => 'NG',
        'currency_code' => 'NGN',
    ],
    [
        'bank_name' => 'STANDARD CHARTERED BANK',
        'bank_code' => '000021',
        'bank_type' => 'Commercial',
        'ussd_code' => null,
        'ussd_transfer_code' => null,
        'bank_logo' => 'https://api.live.redbiller.com/logos/bank/chartered.png',
        'country_code' => 'NG',
        'currency_code' => 'NGN',
    ],
    [
        'bank_name' => 'STANFORD MICROFINANCE BANK',
        'bank_code' => '090162',
        'bank_type' => 'Microfinance',
        'ussd_code' => null,
        'ussd_transfer_code' => null,
        'bank_logo' => 'https://api.live.redbiller.com/logos/bank/default.png',
        'country_code' => 'NG',
        'currency_code' => 'NGN',
    ],
    [
        'bank_name' => 'STERLING BANK',
        'bank_code' => '000001',
        'bank_type' => 'Commercial',
        'ussd_code' => '*822#',
        'ussd_transfer_code' => '*822*5*amount*account_no#',
        'bank_logo' => 'https://api.live.redbiller.com/logos/bank/sterling.png',
        'country_code' => 'NG',
        'currency_code' => 'NGN',
    ],
    [
        'bank_name' => 'STERLING MOBILE (GOMONEY)',
        'bank_code' => '100022',
        'bank_type' => 'Merchant',
        'ussd_code' => null,
        'ussd_transfer_code' => null,
        'bank_logo' => 'https://api.live.redbiller.com/logos/bank/default.png',
        'country_code' => 'NG',
        'currency_code' => 'NGN',
    ],
    [
        'bank_name' => 'SUNTRUST BANK',
        'bank_code' => '000022',
        'bank_type' => 'Commercial',
        'ussd_code' => null,
        'ussd_transfer_code' => null,
        'bank_logo' => 'https://api.live.redbiller.com/logos/bank/default.png',
        'country_code' => 'NG',
        'currency_code' => 'NGN',
    ],
    [
        'bank_name' => 'TAGPAY',
        'bank_code' => '100023',
        'bank_type' => 'Merchant',
        'ussd_code' => null,
        'ussd_transfer_code' => null,
        'bank_logo' => 'https://api.live.redbiller.com/logos/bank/default.png',
        'country_code' => 'NG',
        'currency_code' => 'NGN',
    ],
    [
        'bank_name' => 'TCF MICROFINANCE BANK',
        'bank_code' => '090115',
        'bank_type' => 'Microfinance',
        'ussd_code' => null,
        'ussd_transfer_code' => null,
        'bank_logo' => 'https://api.live.redbiller.com/logos/bank/default.png',
        'country_code' => 'NG',
        'currency_code' => 'NGN',
    ],
    [
        'bank_name' => 'TEASYMOBILE',
        'bank_code' => '100010',
        'bank_type' => 'Merchant',
        'ussd_code' => null,
        'ussd_transfer_code' => null,
        'bank_logo' => 'https://api.live.redbiller.com/logos/bank/default.png',
        'country_code' => 'NG',
        'currency_code' => 'NGN',
    ],
    [
        'bank_name' => 'TITAN TRUST BANK',
        'bank_code' => '000025',
        'bank_type' => 'Commercial',
        'ussd_code' => null,
        'ussd_transfer_code' => null,
        'bank_logo' => 'https://api.live.redbiller.com/logos/bank/default.png',
        'country_code' => 'NG',
        'currency_code' => 'NGN',
    ],
    [
        'bank_name' => 'TRIDENT MICROFINANCE BANK',
        'bank_code' => '090146',
        'bank_type' => 'Microfinance',
        'ussd_code' => null,
        'ussd_transfer_code' => null,
        'bank_logo' => 'https://api.live.redbiller.com/logos/bank/default.png',
        'country_code' => 'NG',
        'currency_code' => 'NGN',
    ],
    [
        'bank_name' => 'TRUSTBOND BANK',
        'bank_code' => '090005',
        'bank_type' => 'Mortgage',
        'ussd_code' => null,
        'ussd_transfer_code' => null,
        'bank_logo' => 'https://api.live.redbiller.com/logos/bank/default.png',
        'country_code' => 'NG',
        'currency_code' => 'NGN',
    ],
    [
        'bank_name' => 'UNION BANK',
        'bank_code' => '000018',
        'bank_type' => 'Commercial',
        'ussd_code' => '*826#',
        'ussd_transfer_code' => '*826*2*amount*account_no#',
        'bank_logo' => 'https://api.live.redbiller.com/logos/bank/union.png',
        'country_code' => 'NG',
        'currency_code' => 'NGN',
    ],
    [
        'bank_name' => 'UNITED BANK FOR AFRICA',
        'bank_code' => '000004',
        'bank_type' => 'Commercial',
        'ussd_code' => '*919#',
        'ussd_transfer_code' => '*919*4*account_no*amount#',
        'bank_logo' => 'https://api.live.redbiller.com/logos/bank/uba.png',
        'country_code' => 'NG',
        'currency_code' => 'NGN',
    ],
    [
        'bank_name' => 'UNITY BANK',
        'bank_code' => '000011',
        'bank_type' => 'Commercial',
        'ussd_code' => '*7799#',
        'ussd_transfer_code' => '*7799*1*account_no*Amount#',
        'bank_logo' => 'https://api.live.redbiller.com/logos/bank/default.png',
        'country_code' => 'NG',
        'currency_code' => 'NGN',
    ],
    [
        'bank_name' => 'VERITE MICROFINANCE BANK',
        'bank_code' => '090123',
        'bank_type' => 'Microfinance',
        'ussd_code' => null,
        'ussd_transfer_code' => null,
        'bank_logo' => 'https://api.live.redbiller.com/logos/bank/default.png',
        'country_code' => 'NG',
        'currency_code' => 'NGN',
    ],
    [
        'bank_name' => 'VFD MICROFINANCE BANK',
        'bank_code' => '090110',
        'bank_type' => 'Microfinance',
        'ussd_code' => null,
        'ussd_transfer_code' => null,
        'bank_logo' => 'https://api.live.redbiller.com/logos/bank/vfd.png',
        'country_code' => 'NG',
        'currency_code' => 'NGN',
    ],
    [
        'bank_name' => 'VIRTUE MICROFINANCE BANK',
        'bank_code' => '090150',
        'bank_type' => 'Microfinance',
        'ussd_code' => null,
        'ussd_transfer_code' => null,
        'bank_logo' => 'https://api.live.redbiller.com/logos/bank/default.png',
        'country_code' => 'NG',
        'currency_code' => 'NGN',
    ],
    [
        'bank_name' => 'VISA MICROFINANCE BANK',
        'bank_code' => '090139',
        'bank_type' => 'Microfinance',
        'ussd_code' => null,
        'ussd_transfer_code' => null,
        'bank_logo' => 'https://api.live.redbiller.com/logos/bank/default.png',
        'country_code' => 'NG',
        'currency_code' => 'NGN',
    ],
    [
        'bank_name' => 'VTNETWORKS',
        'bank_code' => '100012',
        'bank_type' => 'Merchant',
        'ussd_code' => null,
        'ussd_transfer_code' => null,
        'bank_logo' => 'https://api.live.redbiller.com/logos/bank/default.png',
        'country_code' => 'NG',
        'currency_code' => 'NGN',
    ],
    [
        'bank_name' => 'WEMA BANK',
        'bank_code' => '000017',
        'bank_type' => 'Commercial',
        'ussd_code' => '*945#',
        'ussd_transfer_code' => '*945*account_no*amount#',
        'bank_logo' => 'https://api.live.redbiller.com/logos/bank/wema.png',
        'country_code' => 'NG',
        'currency_code' => 'NGN',
    ],
    [
        'bank_name' => 'WETLAND MICROFINANCE BANK',
        'bank_code' => '090120',
        'bank_type' => 'Microfinance',
        'ussd_code' => null,
        'ussd_transfer_code' => null,
        'bank_logo' => 'https://api.live.redbiller.com/logos/bank/default.png',
        'country_code' => 'NG',
        'currency_code' => 'NGN',
    ],
    [
        'bank_name' => 'XSLNCE MICROFINANCE BANK',
        'bank_code' => '090124',
        'bank_type' => 'Microfinance',
        'ussd_code' => null,
        'ussd_transfer_code' => null,
        'bank_logo' => 'https://api.live.redbiller.com/logos/bank/default.png',
        'country_code' => 'NG',
        'currency_code' => 'NGN',
    ],
    [
        'bank_name' => 'YES MICROFINANCE BANK',
        'bank_code' => '090142',
        'bank_type' => 'Microfinance',
        'ussd_code' => null,
        'ussd_transfer_code' => null,
        'bank_logo' => 'https://api.live.redbiller.com/logos/bank/default.png',
        'country_code' => 'NG',
        'currency_code' => 'NGN',
    ],
    [
        'bank_name' => 'ZENITH BANK',
        'bank_code' => '000015',
        'bank_type' => 'Commercial',
        'ussd_code' => '*966#',
        'ussd_transfer_code' => '*966*amount*account_no#',
        'bank_logo' => 'https://api.live.redbiller.com/logos/bank/zenith.png',
        'country_code' => 'NG',
        'currency_code' => 'NGN',
    ],
    [
        'bank_name' => 'ZENITHMOBILE',
        'bank_code' => '100018',
        'bank_type' => 'Merchant',
        'ussd_code' => null,
        'ussd_transfer_code' => null,
        'bank_logo' => 'https://api.live.redbiller.com/logos/bank/default.png',
        'country_code' => 'NG',
        'currency_code' => 'NGN',
    ],
    [
        'bank_name' => 'ZINTERNET - KONGAPAY',
        'bank_code' => '100025',
        'bank_type' => 'Merchant',
        'ussd_code' => null,
        'ussd_transfer_code' => null,
        'bank_logo' => 'https://api.live.redbiller.com/logos/bank/default.png',
        'country_code' => 'NG',
        'currency_code' => 'NGN',
    ],
];
